### ISSUE TITLE
when i run 'npm install', i got the following errors

### ISSUE THREAD

**Issue by pangguoming** [e14n/pump.io#1084]
> bcrypt@0.8.3 install /home/rainbow/WebstormProjects/pump.io-master/node_modules/bcrypt
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.2"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/rainbow/WebstormProjects/pump.io-master/node_modules/bcrypt/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: invalid tar file
gyp ERR! stack     at Extract.Parse._startEntry (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:145:13)
gyp ERR! stack     at Extract.Parse._process (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:127:12)
gyp ERR! stack     at BlockStream.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:47:8)
gyp ERR! stack     at BlockStream.emit (events.js:107:17)
gyp ERR! stack     at BlockStream._emitChunk (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:145:10)
gyp ERR! stack     at BlockStream.write (/usr/local/lib/node_modules/npm/node_modules/block-stream/block-stream.js:45:10)
gyp ERR! stack     at Extract.Parse.write (/usr/local/lib/node_modules/npm/node_modules/tar/lib/parse.js:81:23)

gyp ERR! stack     at Gunzip.ondata (_stream_readable.js:540:20)
gyp ERR! stack     at Gunzip.emit (events.js:107:17)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:163:16)
gyp ERR! System Linux 3.2.0-84-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rainbow/WebstormProjects/pump.io-master/node_modules/bcrypt
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Linux 3.2.0-84-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! bcrypt@0.8.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcrypt@0.8.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bcrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bcrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rainbow/WebstormProjects/pump.io-master/npm-debug.log

**Comment by pangguoming** [comment]
i updated the NodeJs to 0.12 , then it works
