### ISSUE TITLE
Login to a remote account

### ISSUE THREAD

**Issue by mama21mama** [e14n/pump.io#1092]
Error: HTTP Error 401: Error 411: <?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>411 - Length Required</title>
 </head>
 <body>
  <h1>411 - Length Required</h1>
 </body>
</html>

    at Function.<anonymous> (/opt/pump.io/lib/model/credentials.js:161:23)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
    at IncomingMessage.<anonymous> (/opt/pump.io/node_modules/dialback-client/lib/dialbackclient.js:208:21)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by iannsp** [comment]
Hi, did u have more informations about this error? Is this still happening?

**Comment by strugee** [comment]
@mama21mama can you still reproduce this problem? If not, I'll go ahead and close this issue.

**Comment by iannsp** [comment]
hi @strugee  , I already test it and the problem still exists.
please @mama21mama, leave this issue open.

**Comment by strugee** [comment]
@iannsp OK, I'll leave it open. But please provide some more information - what nodes are you seeing this on? Can you provide detailed steps-to-reproduce?

**Comment by iannsp** [comment]
Hi @strugee,
follow screenshots of the failure.
I try the same procedure in another server with the same result(so I think it is not because some environment issue).

![3-failure_screen](https://cloud.githubusercontent.com/assets/40551/12035362/67bae3b4-ae23-11e5-8823-1818bb434f9d.png)
![2-try_login_account_from_other_server](https://cloud.githubusercontent.com/assets/40551/12035363/67bc34da-ae23-11e5-9601-407cbe1dbfb8.png)
![1-user_i_try_follow](https://cloud.githubusercontent.com/assets/40551/12035364/67be4996-ae23-11e5-9b2c-f25c6651d10f.png)
