### ISSUE TITLE
duplicate TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by h4ck3rm1k3** [e14n/pump.io#1105]
On this url:
https://identi.ca/api/user/h4ck3rm1k3/following

TypeError: Cannot read property 'id' of null
    at /opt/pump.io/lib/finishers.js:61:42
    at Array.map (native)
    at addFollowed (/opt/pump.io/lib/finishers.js:60:23)
    at /opt/pump.io/lib/streams.js:700:9
    at Function.collection.links.self.href.URLMaker.makeURL.offset (/opt/pump.io/lib/streams.js:250:17)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/opt/pump.io/node_modules/databank/lib/databankobject.js:238:21)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/opt/pump.io/node_modules/databank/lib/databankobject.js:218:21)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)

**Comment by h4ck3rm1k3** [comment]
https://identi.ca/h4ck3rm1k3/following
TypeError: Cannot read property 'id' of null
    at /opt/pump.io/lib/finishers.js:61:42
    at Array.map (native)
    at addFollowed (/opt/pump.io/lib/finishers.js:60:23)
    at /opt/pump.io/lib/streams.js:700:9
    at Function.collection.links.self.href.URLMaker.makeURL.offset (/opt/pump.io/lib/streams.js:250:17)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/opt/pump.io/node_modules/databank/lib/databankobject.js:238:21)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/opt/pump.io/node_modules/databank/lib/databankobject.js:218:21)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)

**Comment by larjona** [comment]
Thanks for the report.
This is duplicated of #986 ; please have a look there and add your comments there if needed.
Do you mind to close this issue?
Thanks again.
