### ISSUE TITLE
Cannot read property 'sanitize' of null

### ISSUE THREAD

**Issue by h4ck3rm1k3** [e14n/pump.io#1116]
Running locally and using this url
http://127.0.0.1:31337/api/user/test5/inbox/direct/major

```
TypeError: Cannot read property 'sanitize' of null
    at /mnt/data/home/mdupont/experiments/pump.io/lib/streams.js:151:24
    at Array.forEach (native)
    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/lib/streams.js:150:28)
    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/node_modules/databank/lib/databankobject.js:245:21)
    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/node_modules/databank/lib/databankobject.js:225:21)
    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)
    at /mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:83:14
    at check (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:99:9)
```

Log file 
```
{"name":"pump.io","hostname":"mdupont-Aspire-7750G","pid":4549,"component":"connect-databank","level":20,"sid":"CJ6OzlBG8WG8SKQe3SAYB7u6.aPbr5/fIMRZ+R+73tMFUj+SauP+ckMym9u7iYC5tmVI","session":{"lastAccess":1445338108613,"cookie":{"originalMaxAge":14400000,"expires":"2015-10-20T14:48:28.628Z","httpOnly":true,"path":"/"},"sid":"CJ6OzlBG8WG8SKQe3SAYB7u6.aPbr5/fIMRZ+R+73tMFUj+SauP+ckMym9u7iYC5tmVI","principal":{"id":"http://127.0.0.1:31337/api/user/test5/profile","objectType":"person"}},"msg":"Got session.","time":"2015-10-20T10:48:44.204Z","v":0}
{"name":"pump.io","hostname":"mdupont-Aspire-7750G","pid":4549,"req_id":"a769c86a-7df2-4069-9f73-789161ea0266","component":"web","level":20,"msg":"","session":{"lastAccess":1445338124204,"cookie":{"originalMaxAge":14400000,"expires":"2015-10-20T14:48:28.628Z","httpOnly":true,"path":"/"},"sid":"CJ6OzlBG8WG8SKQe3SAYB7u6.aPbr5/fIMRZ+R+73tMFUj+SauP+ckMym9u7iYC5tmVI","principal":{"id":"http://127.0.0.1:31337/api/user/test5/profile","objectType":"person"}},"time":"2015-10-20T10:48:44.204Z","v":0}
{"name":"pump.io","hostname":"mdupont-Aspire-7750G","pid":4549,"req_id":"a769c86a-7df2-4069-9f73-789161ea0266","component":"web","level":20,"msg":"","principal":{"id":"http://127.0.0.1:31337/api/user/test5/profile","type":"person"},"time":"2015-10-20T10:48:44.207Z","v":0}
{"name":"pump.io","hostname":"mdupont-Aspire-7750G","pid":4549,"req_id":"a769c86a-7df2-4069-9f73-789161ea0266","component":"web","level":20,"msg":"","user":{"nickname":"test5","updated":"2015-10-19T02:08:26Z","published":"2015-10-19T02:08:26Z","_passwordHash":"$2a$10$fidjwyX/z/qz6WYc6yRJ3.Rw8DKoyA/G7y6oWxOCYFI.WxA2VbIoC","profile":{"objectType":"person","id":"http://127.0.0.1:31337/api/user/test5/profile"}},"time":"2015-10-20T10:48:44.209Z","v":0}
{"name":"pump.io","hostname":"mdupont-Aspire-7750G","pid":4549,"level":50,"err":{"message":"Cannot read property 'sanitize' of null","name":"TypeError","stack":"TypeError: Cannot read property 'sanitize' of null\n    at /mnt/data/home/mdupont/experiments/pump.io/lib/streams.js:151:24\n    at Array.forEach (native)\n    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/lib/streams.js:150:28)\n    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)\n    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/node_modules/databank/lib/databankobject.js:245:21)\n    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)\n    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/node_modules/databank/lib/databankobject.js:225:21)\n    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)\n    at /mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:83:14\n    at check (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:99:9)"},"req":{"method":"GET","url":"/api/user/test5/inbox/direct/major","headers":{"host":"127.0.0.1:31337","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.1.1","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","cookie":"connect.sid=CJ6OzlBG8WG8SKQe3SAYB7u6.aPbr5%2FfIMRZ%2BR%2B73tMFUj%2BSauP%2BckMym9u7iYC5tmVI","connection":"keep-alive","cache-control":"max-age=0"},"remoteAddress":"127.0.0.1","remotePort":43908},"msg":"Cannot read property 'sanitize' of null","time":"2015-10-20T10:48:44.218Z","v":0}
{"name":"pump.io","hostname":"mdupont-Aspire-7750G","pid":4549,"component":"connect-databank","level":20,"sid":"CJ6OzlBG8WG8SKQe3SAYB7u6.aPbr5/fIMRZ+R+73tMFUj+SauP+ckMym9u7iYC5tmVI","session":{"lastAccess":1445338124204,"cookie":{"originalMaxAge":14400000,"expires":"2015-10-20T14:48:44.219Z","httpOnly":true,"path":"/"},"sid":"CJ6OzlBG8WG8SKQe3SAYB7u6.aPbr5/fIMRZ+R+73tMFUj+SauP+ckMym9u7iYC5tmVI","principal":{"id":"http://127.0.0.1:31337/api/user/test5/profile","objectType":"person"}},"msg":"Saved session.","time":"2015-10-20T10:48:44.224Z","v":0}
{"name":"pump.io","hostname":"mdupont-Aspire-7750G","pid":4549,"req_id":"a769c86a-7df2-4069-9f73-789161ea0266","component":"web","level":30,"req":{"method":"GET","url":"/api/user/test5/inbox/direct/major","headers":{"host":"127.0.0.1:31337","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Firefox/38.0 Iceweasel/38.1.1","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate","cookie":"connect.sid=CJ6OzlBG8WG8SKQe3SAYB7u6.aPbr5%2FfIMRZ%2BR%2B73tMFUj%2BSauP%2BckMym9u7iYC5tmVI","connection":"keep-alive","cache-control":"max-age=0"},"remoteAddress":"127.0.0.1","remotePort":43908},"res":{"statusCode":500,"header":"HTTP/1.1 500 Internal Server Error\r\nX-Powered-By: Express\r\nServer: pump.io/0.3.0 express/2.5.11 node.js/v4.2.1\r\nContent-Type: text/plain\r\nSet-Cookie: connect.sid=CJ6OzlBG8WG8SKQe3SAYB7u6.aPbr5%2FfIMRZ%2BR%2B73tMFUj%2BSauP%2BckMym9u7iYC5tmVI; path=/; expires=Tue, 20 Oct 2015 14:48:28 GMT; httpOnly\r\nDate: Tue, 20 Oct 2015 10:48:44 GMT\r\nConnection: keep-alive\r\nTransfer-Encoding: chunked\r\n\r\n"},"serverTime":24,"principal":{"id":"http://127.0.0.1:31337/api/user/test5/profile","type":"person"},"client":{"title":"<none>"},"msg":"","time":"2015-10-20T10:48:44.224Z","v":0}

```

Node debug console
```
HTTP 4549: SERVER socketOnParserExecute 461
NET 4549: pipe false undefined
NET 4549: _read
NET 4549: _read wait for connection
NET 4549: afterConnect
NET 4549: _read
NET 4549: Socket._read readStart
NET 4549: onread 392
NET 4549: got data
NET 4549: _read
MODULE 4549: Module._load REQUEST  ./person parent: /mnt/data/home/mdupont/experiments/pump.io/lib/model/activityobject.js
MODULE 4549: RELATIVE: requested:./person set ID to: /mnt/data/home/mdupont/experiments/pump.io/lib/model/person from /mnt/data/home/mdupont/experiments/pump.io/lib/model/activityobject.js
MODULE 4549: looking for "/mnt/data/home/mdupont/experiments/pump.io/lib/model/person" in ["/mnt/data/home/mdupont/experiments/pump.io/lib/model"]
get ID http://127.0.0.1:31337/api/user/test5/profile
NET 4549: onread 869
NET 4549: got data
read id:http://127.0.0.1:31337/api/user/test5/profile
read value:[object Object]
read value[person http://127.0.0.1:31337/api/user/test5/profile]
MODULE 4549: Module._load REQUEST  ../upgrader parent: /mnt/data/home/mdupont/experiments/pump.io/lib/model/person.js
MODULE 4549: RELATIVE: requested:../upgrader set ID to: /mnt/data/home/mdupont/experiments/pump.io/lib/upgrader from /mnt/data/home/mdupont/experiments/pump.io/lib/model/person.js
MODULE 4549: looking for "/mnt/data/home/mdupont/experiments/pump.io/lib/upgrader" in ["/mnt/data/home/mdupont/experiments/pump.io/lib/model"]
NET 4549: _read
NET 4549: onread 52
NET 4549: got data
NET 4549: _read
NET 4549: onread 285
NET 4549: got data
get IDtest5
NET 4549: _read
NET 4549: onread 285
NET 4549: got data
read id:test5
read value:[object Object]
read value[user test5]
MODULE 4549: Module._load REQUEST  ./person parent: /mnt/data/home/mdupont/experiments/pump.io/lib/model/activityobject.js
MODULE 4549: RELATIVE: requested:./person set ID to: /mnt/data/home/mdupont/experiments/pump.io/lib/model/person from /mnt/data/home/mdupont/experiments/pump.io/lib/model/activityobject.js
MODULE 4549: looking for "/mnt/data/home/mdupont/experiments/pump.io/lib/model/person" in ["/mnt/data/home/mdupont/experiments/pump.io/lib/model"]
get IDhttp://127.0.0.1:31337/api/user/test5/profile
NET 4549: _read
NET 4549: onread 869
NET 4549: got data
read id:http://127.0.0.1:31337/api/user/test5/profile
read value:[object Object]
read value[person http://127.0.0.1:31337/api/user/test5/profile]
MODULE 4549: Module._load REQUEST  ../upgrader parent: /mnt/data/home/mdupont/experiments/pump.io/lib/model/person.js
MODULE 4549: RELATIVE: requested:../upgrader set ID to: /mnt/data/home/mdupont/experiments/pump.io/lib/upgrader from /mnt/data/home/mdupont/experiments/pump.io/lib/model/person.js
MODULE 4549: looking for "/mnt/data/home/mdupont/experiments/pump.io/lib/upgrader" in ["/mnt/data/home/mdupont/experiments/pump.io/lib/model"]
get IDuser:test5:inbox:direct:major
NET 4549: _read
NET 4549: onread 96
NET 4549: got data
read id:user:test5:inbox:direct:major
read value:[object Object]
read value[stream user:test5:inbox:direct:major]
NET 4549: _read
NET 4549: onread 61
NET 4549: got data
NET 4549: _read
NET 4549: onread 126
NET 4549: got data
NET 4549: _read
NET 4549: onread 98
NET 4549: got data
NET 4549: _read
NET 4549: onread 155
NET 4549: got data
NET 4549: _read
NET 4549: onread 5
NET 4549: got data
NET 4549: _read
TypeError: Cannot read property 'sanitize' of null
    at /mnt/data/home/mdupont/experiments/pump.io/lib/streams.js:151:24
    at Array.forEach (native)
    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/lib/streams.js:150:28)
    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/node_modules/databank/lib/databankobject.js:245:21)
    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/mnt/data/home/mdupont/experiments/pump.io/node_modules/databank/lib/databankobject.js:225:21)
    at next (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:51:23)
    at /mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:83:14
    at check (/mnt/data/home/mdupont/experiments/pump.io/node_modules/step/lib/step.js:99:9)
NET 4549: onread 392
NET 4549: got data
NET 4549: _read
NET 4549: onread 392
NET 4549: got data
NET 4549: _read
NET 4549: onread 8
NET 4549: got data
NET 4549: _read
HTTP 4549: write ret = true
HTTP 4549: outgoing message end.
NET 4549: afterWrite 0
NET 4549: afterWrite call cb
NET 4549: _onTimeout
NET 4549: onSocketFinish
NET 4549: oSF: not ended, call shutdown()
NET 4549: destroy undefined
NET 4549: destroy
NET 4549: close
NET 4549: close handle
NET 4549: destroy undefined
NET 4549: destroy
NET 4549: already destroyed, fire error callbacks
NET 4549: afterShutdown destroyed=true ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: [],
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: false,
  endEmitted: false,
  reading: true,
  sync: false,
  needReadable: true,
  emittedReadable: false,
  readableListening: false,
  defaultEncoding: 'utf8',
  ranOut: false,
  awaitDrain: 0,
  readingMore: false,
  decoder: 
   { encoding: 'utf8',
     surrogateSize: 3,
     charBuffer: <Buffer 20 31 35 20 4f 63>,
     charReceived: 0,
     charLength: 0 },
  encoding: 'utf8',
  resumeScheduled: false }
NET 4549: emit close
NET 4528: onread -4095
NET 4558: onread -4095
NET 4538: onread -4095
NET 4528: EOF
NET 4558: EOF
NET 4538: EOF
NET 4528: onSocketEnd ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: [],
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: true,
  endEmitted: false,
  reading: false,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  defaultEncoding: 'utf8',
  ranOut: false,
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null,
  resumeScheduled: false }
NET 4558: onSocketEnd ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: [],
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: true,
  endEmitted: false,
  reading: false,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  defaultEncoding: 'utf8',
  ranOut: false,
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null,
  resumeScheduled: false }
NET 4558: onSocketFinish
NET 4538: onSocketEnd ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: [],
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: true,
  endEmitted: false,
  reading: false,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  defaultEncoding: 'utf8',
  ranOut: false,
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null,
  resumeScheduled: false }
NET 4528: onSocketFinish
NET 4538: onSocketFinish
NET 4558: oSF: ended, destroy ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: [],
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  defaultEncoding: 'utf8',
  ranOut: false,
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null,
  resumeScheduled: false }
NET 4558: destroy undefined
NET 4538: oSF: ended, destroy ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: [],
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  defaultEncoding: 'utf8',
  ranOut: false,
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null,
  resumeScheduled: false }
NET 4558: destroy
NET 4558: close
NET 4538: destroy undefined
NET 4558: close handle
NET 4538: destroy
NET 4538: close
NET 4538: close handle
NET 4558: has server
NET 4558: SERVER _emitCloseIfDrained
NET 4558: SERVER handle? true   connections? 0
NET 4538: has server
NET 4538: SERVER _emitCloseIfDrained
NET 4558: emit close
HTTP 4558: server socket close
NET 4528: oSF: ended, destroy ReadableState {
  objectMode: false,
  highWaterMark: 16384,
  buffer: [],
  length: 0,
  pipes: null,
  pipesCount: 0,
  flowing: true,
  ended: true,
  endEmitted: true,
  reading: false,
  sync: false,
  needReadable: false,
  emittedReadable: false,
  readableListening: false,
  defaultEncoding: 'utf8',
  ranOut: false,
  awaitDrain: 0,
  readingMore: false,
  decoder: null,
  encoding: null,
  resumeScheduled: false }
NET 4528: destroy undefined
NET 4528: destroy
NET 4528: close
NET 4528: close handle
NET 4528: has server
NET 4528: SERVER _emitCloseIfDrained
NET 4538: SERVER handle? true   connections? 0
NET 4528: SERVER handle? true   connections? 0
NET 4528: emit close
HTTP 4528: server socket close
NET 4538: emit close
HTTP 4538: server socket close
NET 4533: onread -4095
NET 4533: EOF

```

**Comment by h4ck3rm1k3** [comment]
The activityFeed function has the problem.
The line of code is :
https://github.com/e14n/pump.io/blob/1029ac71b94dec2b51f6b2aa461b5b2a514e585a/lib/streams.js#L151

```
   activities.forEach(function(act) {
                    act.sanitize(principal);
                });
```

**Comment by h4ck3rm1k3** [comment]
I think this is a result of the same cause as #1117

**Comment by h4ck3rm1k3** [comment]
The system does not have a dns and the dialback does not work. The server gets into an inconsistant state because of that.
